// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_DELETED Status = 0
	Status_CREATED Status = 1
	Status_FROZEN  Status = 2
)

var Status_name = map[int32]string{
	0: "DELETED",
	1: "CREATED",
	2: "FROZEN",
}

var Status_value = map[string]int32{
	"DELETED": 0,
	"CREATED": 1,
	"FROZEN":  2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type User struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string     `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Age                  int32      `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Email                string     `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Favors               *UserFavor `protobuf:"bytes,5,opt,name=favors,proto3" json:"favors,omitempty"`
	Power                *Power     `protobuf:"bytes,6,opt,name=power,proto3" json:"power,omitempty"`
	Team                 *Team      `protobuf:"bytes,7,opt,name=team,proto3" json:"team,omitempty"`
	Labels               *Labels    `protobuf:"bytes,8,opt,name=labels,proto3" json:"labels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFavors() *UserFavor {
	if m != nil {
		return m.Favors
	}
	return nil
}

func (m *User) GetPower() *Power {
	if m != nil {
		return m.Power
	}
	return nil
}

func (m *User) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *User) GetLabels() *Labels {
	if m != nil {
		return m.Labels
	}
	return nil
}

type UserFavor struct {
	Favors               []string `protobuf:"bytes,1,rep,name=favors,proto3" json:"favors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFavor) Reset()         { *m = UserFavor{} }
func (m *UserFavor) String() string { return proto.CompactTextString(m) }
func (*UserFavor) ProtoMessage()    {}
func (*UserFavor) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserFavor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFavor.Unmarshal(m, b)
}
func (m *UserFavor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFavor.Marshal(b, m, deterministic)
}
func (m *UserFavor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFavor.Merge(m, src)
}
func (m *UserFavor) XXX_Size() int {
	return xxx_messageInfo_UserFavor.Size(m)
}
func (m *UserFavor) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFavor.DiscardUnknown(m)
}

var xxx_messageInfo_UserFavor proto.InternalMessageInfo

func (m *UserFavor) GetFavors() []string {
	if m != nil {
		return m.Favors
	}
	return nil
}

type UserID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status               Status   `protobuf:"varint,2,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserID) Reset()         { *m = UserID{} }
func (m *UserID) String() string { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()    {}
func (*UserID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserID.Unmarshal(m, b)
}
func (m *UserID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserID.Marshal(b, m, deterministic)
}
func (m *UserID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserID.Merge(m, src)
}
func (m *UserID) XXX_Size() int {
	return xxx_messageInfo_UserID.Size(m)
}
func (m *UserID) XXX_DiscardUnknown() {
	xxx_messageInfo_UserID.DiscardUnknown(m)
}

var xxx_messageInfo_UserID proto.InternalMessageInfo

func (m *UserID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserID) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_DELETED
}

func init() {
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*UserFavor)(nil), "proto.UserFavor")
	proto.RegisterType((*UserID)(nil), "proto.UserID")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0x49, 0x93, 0xe9, 0xd7, 0x1b, 0x2d, 0xe1, 0x22, 0x32, 0x74, 0x63, 0x88, 0x08,
	0xc1, 0x45, 0x16, 0xfa, 0x00, 0x22, 0x26, 0x85, 0x40, 0x51, 0x19, 0xeb, 0xc6, 0xdd, 0x14, 0xc6,
	0x3f, 0x90, 0x34, 0x21, 0x93, 0xea, 0x5b, 0xfb, 0x0c, 0x32, 0x77, 0xa6, 0x59, 0xe5, 0x9e, 0x73,
	0x7e, 0xe4, 0x9e, 0xb9, 0x00, 0x07, 0xa3, 0x87, 0xa2, 0x1f, 0xba, 0xb1, 0xc3, 0x88, 0x3e, 0xab,
	0xb8, 0x51, 0x3b, 0xdd, 0x14, 0x5e, 0xf4, 0xdd, 0xcf, 0x11, 0x58, 0xc1, 0xa8, 0x55, 0xeb, 0xe6,
	0xec, 0x97, 0x41, 0xf8, 0x6a, 0xf4, 0x80, 0x08, 0xe1, 0x5e, 0xb5, 0x5a, 0xb0, 0x94, 0xe5, 0x0b,
	0x49, 0x33, 0x9e, 0x41, 0xd4, 0x7f, 0x76, 0x7b, 0x2d, 0x02, 0x32, 0x9d, 0xc0, 0x04, 0x66, 0xea,
	0x43, 0x8b, 0x59, 0xca, 0xf2, 0x48, 0xda, 0xd1, 0x72, 0xba, 0x55, 0x5f, 0x8d, 0x08, 0x1d, 0x47,
	0x02, 0x73, 0xe0, 0xef, 0xea, 0xbb, 0x1b, 0x8c, 0x88, 0x52, 0x96, 0xc7, 0x37, 0x89, 0x5b, 0x59,
	0xd8, 0x75, 0x6b, 0x1b, 0x48, 0x9f, 0x63, 0x06, 0x11, 0xf5, 0x13, 0x9c, 0xc0, 0x13, 0x0f, 0x3e,
	0x5b, 0x4f, 0xba, 0x08, 0x2f, 0x20, 0xb4, 0xb5, 0xc5, 0x9c, 0x90, 0xd8, 0x23, 0x5b, 0xad, 0x5a,
	0x49, 0x01, 0x5e, 0x01, 0xa7, 0x17, 0x1b, 0xf1, 0x9f, 0x90, 0x53, 0x8f, 0x6c, 0xc8, 0x94, 0x3e,
	0xcc, 0x2e, 0x61, 0x31, 0x15, 0xc0, 0xf3, 0xa9, 0x22, 0x4b, 0x67, 0xf9, 0xe2, 0x58, 0x28, 0xbb,
	0x03, 0x6e, 0xa1, 0xba, 0xc4, 0x25, 0x04, 0x75, 0xe9, 0x8f, 0x12, 0xd4, 0xa5, 0xdd, 0x62, 0x46,
	0x35, 0x1e, 0x0c, 0xdd, 0x64, 0x39, 0x6d, 0x79, 0x21, 0x53, 0xfa, 0xf0, 0xba, 0x00, 0xee, 0x1c,
	0x8c, 0x61, 0x5e, 0x56, 0x9b, 0x6a, 0x5b, 0x95, 0xc9, 0x3f, 0x2b, 0x1e, 0x64, 0x75, 0x6f, 0x05,
	0x43, 0x00, 0xbe, 0x96, 0x4f, 0x6f, 0xd5, 0x63, 0x12, 0xec, 0x38, 0xfd, 0xe5, 0xf6, 0x2f, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0x21, 0x16, 0xc5, 0xc8, 0x01, 0x00, 0x00,
}
